export enum TermsType {
  USING_OF_SERVICE = 'USING_OF_SERVICE',
  PROCESSING_POLICY_OF_PRIVATE_INFO = 'PROCESSING_POLICY_OF_PRIVATE_INFO',
  USING_OF_PRIVATE_INFO = 'USING_OF_PRIVATE_INFO',
  OFFERING_PRIVATE_INFO_TO_THIRD_PARTY = 'OFFERING_PRIVATE_INFO_TO_THIRD_PARTY',
}
